### ISSUE TITLE
Inputs vs Activities

### ISSUE THREAD

**Issue by durosity** [smockle/homebridge-harmony-tv#10]
I'm curious as to the input references in the config json.  Can these be mapped to activities?  I'm just thinking from a use-case of trying to imitate the harmony app as best as possible.. as in Inputs being the activities, changing activities will change the direction pad, etc to the device used in the activity you selected, etc.

**Comment by smockle** [comment]
That’s an intriguing idea that I hadn’t considered! What you’re proposing—dynamically re-mapping the iOS remote app buttons depending on the selected input—sounds possible to me. How would you recommend structuring the `config.json` to support this?

**Comment by durosity** [comment]
I'm at work at the moment so don't quite have the time I need to properly think about that until tonight.. but I'd imagine it'd be along the lines of defining the hub as you're currently doing, then listing the activities you want it to show, then having your plugin action the command based on that activity that's currently running.  I'm not familiar with the limitations of the homekit tv functionality so I'm not sure if that's possible or not.. but it certainly seems plausible from my point of view.

On a side note it'd be good if this could support multiple hubs.  I currently have 3 in my house with a plan to add 2 more soon!

**Comment by BetoRn** [comment]
On the npm published version of homebridge-harmonyhub plugin 0.3.0-alpha.2 the author managed to create volume controls that appear on the Eve home app, this effectively control the volume without any configuration on the config.json

**Comment by smockle** [comment]
> Would there be a way to use this as a custom_component in Home Assistant?

@CMaxim77 I don’t use Home Assistant, but after investigating I discovered significant hurdles:

1. Home Assistant expects Python code in `custom_components`[¹](https://developers.home-assistant.io/docs/en/dev_101_index.html), and this Homebridge plugin is written in JavaScript using Homebridge-specific APIs.

2. If this plugin was rewritten in Python with _Home Assistant_-specific APIs, Home Assistant would not expose TVs to HomeKit, because Home Assistant’s built-in HomeKit integration does not support TVs[²](https://www.home-assistant.io/components/homekit/#supported-components).

If you want Home Assistant to be able to trigger Harmony Activities, this component may work for you: https://www.home-assistant.io/components/remote.harmony/.

⁂

¹ https://developers.home-assistant.io/docs/en/dev_101_index.html
² https://www.home-assistant.io/components/homekit/#supported-components

**Comment by CMaxim77** [comment]
I do use the harmony hub with home Assistant. I can control my tv with it, but I really do like how this integrates with HomeKit. It is so much cleaner looking for sure! I understand there’s a huge difference in the coding. Maybe eventually somebody in the community will pick this project up. Unfortunately I’m not smart enough to do it yet! I truly appreciate you taking the time to reply to my question. I’ll be following your progress for sure! I absolutely love this stuff!

**Comment by smockle** [comment]
@durosity When you opened this issue, you suggested:
> Inputs being the activities, changing activities will change the direction pad, etc to the device used in the activity

According to its README, the [`homebridge-harmony` plugin](https://github.com/nicoduj/homebridge-harmony) supports this:
> iOS 12.2 TV mode…this mode will focus on harmony hub activities : each activity of the hub is mapped to an input. A main activity is linked to the on/off switch of the accessory. Buttons on the remote app and volume controls will be binded to the one defined in the activity…

I haven’t tried that particular feature, but I have used that plugin. You might want to check it out.

**Comment by smockle** [comment]
Since `homebridge-harmony` supports activities-as-inputs, I’d like to avoid duplicating that feature in `homebridge-harmony-tv`, to keep this plugin focused and maintainable. After considering what I can test and support, the target use case of this plugin will be “control a non-smart TV in HomeKit via a Harmony Hub”, not “use HomeKit as an interface for all Harmony features”. I see how the latter will be useful to folks, so I both a. appreciate the suggestion here and b. am glad `homebridge-harmony` exists.

**Comment by durosity** [comment]
Yeah I’d agree it makes more sense to not have overlap.  I only suggested it on here as at that time no other plugin worked that way and you seemed to be actively developing it!
