### ISSUE TITLE
Error when trying to run hubinfo.js

### ISSUE THREAD

**Issue by overflywingo** [smockle/homebridge-harmony-tv#12]
Hi, 
Installation went fine , but I can go further with the hubinfo.js 

Thanks for your help 

pi@raspberrypi:~ $ node scripts/hubinfo.js $HOST
module.js:545
    throw err;
    ^

Error: Cannot find module '/home/pi/scripts/hubinfo.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by smockle** [comment]
Hi @overflywingo, thanks for trying out the plugin! A few questions:

1. Which version of Node.js are you using? (`node --version`)
2. Which version of the plugin do you have installed? (`npm ls -g --depth=0 | grep homebridge-harmony-tv-smockle`)

From the output you‘ve shared above, it looks like your working directory is `/home/pi` rather than the plugin directory. If your node version and plugin version are up-to-date, you have a couple options to resolve this:

* First, change to the plugin directory with `cd $(npm root -g)/homebridge-harmony-tv-smockle`, then run the commands in the README (e.g. `node scripts/hubinfo.js $HOST`)

or

* Run the commands in the README with the full path to `hubinfo.js`, e.g. `node "$(npm root -g)/homebridge-harmony-tv-smockle/scripts/hubinfo.js" $HOST`

**Comment by overflywingo** [comment]
Hi, ... excellent .. thanks for your clear explanations.  I've found now the right hubinfo's :) 

I followed your 1st proposal (* First, change to the plugin directory with `cd "$(npm root -g)/homebridge-harmony-tv-smockle"`, then run the commands in the README) 

Fyi , I'm running Node v9.9.0 and homebridge-harmony-tv plugin v2.0.5

I'm now able to pursue with the plugin configuration
